services:
  client:
    build:
      context: ./Client
      dockerfile: Dockerfile
    container_name: carpool-client
    ports:
      - "3000:80" # host 3000 → Nginx 80
    depends_on:
      - server
      - customerservice
    networks:
      - app-network

  customerservice:
    build:
      context: ./CustomerService
      dockerfile: Dockerfile
    container_name: customer-service
    ports:
      - "4000:4000"
    env_file:
      - ./CustomerService/.env
    networks:
      - app-network

  server:
    build:
      context: ./Server
      dockerfile: Dockerfile
    container_name: carpool-service
    ports:
      - "5000:5000"
    env_file:
      - ./Server/.env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
